### ISSUE TITLE
Couldn't start the server! Too low port?

### ISSUE THREAD

**Issue by vrchlabak** [shusain93/OSXMessageProxy#12]
First, I love this project and hope to eventually get it working. At this point, I have been able to connect the server to my Galaxy S8+ and can see the message in the AndromedaB app. I can also respond. However, I am not getting any notifications, though I have set up the ITTT and Pushbullet on my phone correctly. The biggest issue is that the Andromeda app is not refreshing on it's own = I have to terminate it and reopen it again to get fresh messages (or any edits in messages).

Also, I can't compose new messages from the AndromedaB app.

Thanks in advance for your help!

**Comment by shusain93** [comment]
Can you attach the logs from your home directory? Can you send a screenshot of your IFTTT recipie?

**Comment by vrchlabak** [comment]
Thanks. Can I respond to this email or post on the forum?

On Jun 13, 2017, at 11:40 AM, Salman Husain <notifications@github.com> wrote:

Can you attach the logs from your home directory? Can you send a screenshot of your IFTTT recipie?

**Comment by vrchlabak** [comment]
Here is the log and screenshots. Please note, I took out the API protection key for security reasons. Thanks for your help!

![screen shot 2017-06-13 at 11 49 34 am](https://user-images.githubusercontent.com/7145322/27099029-6bb02a20-502e-11e7-83a5-7c875a519a09.png)


![screen shot 2017-06-13 at 11 48 10 am](https://user-images.githubusercontent.com/7145322/27098987-3d6e5268-502e-11e7-864f-57656d6a5567.png)

![screen shot 2017-06-13 at 11 46 31 am](https://user-images.githubusercontent.com/7145322/27098936-07961a40-502e-11e7-9865-b035e1b99a50.png)


[2017-06-13.txt](https://github.com/shusain93/OSXMessageProxy/files/1072528/2017-06-13.txt)

**Comment by vrchlabak** [comment]
Also, to clarify, the server is working when I initially launch the app (via command). Then it eventually gives me the above message. 

Both ports are reserved and open on the router. 

Thanks.

**Comment by vrchlabak** [comment]
So, the notifications started to work, using the same settings I have put in yesterday. not sure why it took a day, but it's on. With that said, when I click on a notification in the drawer, the app opens, but it's not refreshed = doesn't open the actual conversation (unless I terminate it and open it again).

thanks!!!

**Comment by shusain93** [comment]
The refreshing issue is also fixed in the dev branch but I'm really not sure about the server instance. It'll only ever do this on start (i.e. when the server starts up when the app launches, so if there's an issue later you will not get this message) so it could be that the port is taken by the crashed instance of the proxy.  When the server shows this status, can you still access it? If not, can you run `lsof -n -i4TCP:8735| grep LISTEN`? You should hopefully see nothing but if you do that means some other process is still locking the port.

I've never seen this problem before, pretty odd.

**Comment by vrchlabak** [comment]
Thanks.
It gives me this error in the script:
[ERROR] Failed binding IPv4 listening socket: Address already in use (48)

Also, how can I get the developer branch app and script?

**Comment by shusain93** [comment]
You'd need to download and setup Android Studio since it's not ready to be released yet so I haven't build an installable app. 

It looks like It's not freeing the port on crash. Do you by chance have multiple instances running? Even if you don't, could you reboot and try running just using the script (I really can't recommend running off just the .app ever). If the server can't bind to the port, it'll never be able to communicate and that'll break the refreshing or loading anything but you will still receive notifications since that's not part of the API server

**Comment by vrchlabak** [comment]
I have android studio and can upload the app from it. As long as know how to do it :).

Here is the screenshots of the app and terminal running. I get the terminal process going by double clicking on the command (in the same folder. it crashes after I minimize it to the dock and reopen it again- otherwise it seems to be running fine. Could that be the issue?

![screen shot 2017-06-13 at 3 10 10 pm](https://user-images.githubusercontent.com/7145322/27106937-6de55740-504a-11e7-98bc-15f56a068e54.png)

![screen shot 2017-06-13 at 3 12 56 pm](https://user-images.githubusercontent.com/7145322/27107024-de5c012c-504a-11e7-97e1-c52878558d24.png)

**Comment by shusain93** [comment]
Just download the project from here https://github.com/shusain93/Andromeda-iMessage/archive/master.zip and then point android studio at the project. It'll download a bunch of stuff but should build and run.

All of those "errors" in the console is just OSX being weird, the standard system console is full of that even when the server isn't running. I also seem to have this issue, so I'll look into it on my end. In the meantime I'll suggest that you just hide it with commmand-h instead of minimizing it

**Comment by vrchlabak** [comment]
will do, thanks for your help. All seems to be working great now, except for the refreshing of the app, which I will try to fix tonight by compiling the app from the developer built.

Thanks for all of your efforts. this is a great idea (even I though don't understand the guts of it) and will allow me to actually use the S8+, which is great machine, till the IP8 comes out :).

**Comment by vrchlabak** [comment]
1.2.2 installed and seems to be refreshing now. Is there any way to compose / start conversation straight from the app on Android?

Thanks for all of your help.

**Comment by shusain93** [comment]
No,  but there's an active issue open for it on the android app project page

**Comment by vrchlabak** [comment]
Ok. Thanks again!!
-------- Original message --------From: Salman Husain <notifications@github.com> Date: 6/13/17  18:18  (GMT-08:00) To: shusain93/OSXMessageProxy <OSXMessageProxy@noreply.github.com> Cc: vrchlabak <danielerman@gmail.com>, Author <author@noreply.github.com> Subject: Re: [shusain93/OSXMessageProxy] Couldn't start the server! Too low
  port? (#12) 
No,  but there's an active issue open for it on the android app project page

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shusain93/OSXMessageProxy","title":"shusain93/OSXMessageProxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shusain93/OSXMessageProxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shusain93 in #12: No,  but there's an active issue open for it on the android app project page"}],"action":{"name":"View Issue","url":"https://github.com/shusain93/OSXMessageProxy/issues/12#issuecomment-308292087"}}}
