### ISSUE TITLE
Firebase Configuration/Authentication?

### ISSUE THREAD

**Issue by chattahippie** [shusain93/OSXMessageProxy#24]
Hi Salman,

I am trying to build this project from source to run on my personal Firebase DB.  I have been unable to find references to how your Firebase DB is authenticated. Can you post or contact me with details of how you are authenticating the users?

**Comment by shusain93** [comment]
My Firebase setup isn’t currently working. It’s only in the main repo because I forgot to use a feature branch. 

It’s a commented out disaster and there’s no UI for creating an account. In the Firebase connector class there’s a section of commented out code which calls the function “createAccount”. That’ll create an account with an email and password. Currently the Firebase implantation is working from the server, it syncs all the conversations as they come in. I didn’t get around to modifying the android app yet. If you want to do this on your own Firebase instance you can just swap out the config file and watch the real time database.

**Comment by chattahippie** [comment]
Awesome, thanks for the help

**Comment by shusain93** [comment]
If you’re familiar with Firebase I’d love some help with efficiency because I’ve literally just started using Firebase (without reading the docs lol) and got it working thanks to good design by google. The goal with using Firebase is that we can have the message database in constant real-time sync and so instead of requesting the whole database every time we fan just get tiny updates. That’ll make the app faster and more reliable and it’ll hopefully let us have SMS and iMessage in the app one day (pipe dream, don’t count on it)

**Comment by chattahippie** [comment]
I'm not a Firebase expert, but I'll make a pull request if I make any headway on making a secure connection.  I'm just trying to get it up and running at the moment :)

**Comment by shusain93** [comment]
You’ll also need to uncomment this

https://github.com/shusain93/OSXMessageProxy/blob/master/MessageProxy/ViewController.swift#L45

In order for the Firebase portion to run. Like I said, it’s a commented out disaster :P
